### ISSUE TITLE
pydantic.error_wrappers.ValidationError: 1 validation error for ConversationalChatAgent

### ISSUE THREAD

**Issue by ALERTua** [FOLLGAD/sherlock#2]
I tried Python 3.10 and 3.11 @ Windows 11. No luck.
```
Traceback (most recent call last):
  File "C:\Users\alexe\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\231.8109.197\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexe\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\231.8109.197\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\_Backup\Users\alexe\PycharmProjects\ha_sherlock\sherlock.py", line 55, in <module>
    agent_chain = initialize_agent(
                  ^^^^^^^^^^^^^^^^^
  File "C:\_Backup\Users\alexe\PycharmProjects\ha_sherlock\venv311\Lib\site-packages\langchain\agents\initialize.py", line 58, in initialize_agent
    agent_obj = agent_cls.from_llm_and_tools(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_Backup\Users\alexe\PycharmProjects\ha_sherlock\venv311\Lib\site-packages\langchain\agents\conversational_chat\base.py", line 155, in from_llm_and_tools
    return cls(
           ^^^^
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ConversationalChatAgent
template_tool_response
  field required (type=value_error.missing)
```

**Comment by FOLLGAD** [comment]
Thanks for trying it out! This should be fixed now, run `pip uninstall langchain` then install dependencies again `pip install -r requirements.txt`

**Comment by ALERTua** [comment]
The error is gone. Thank you
